// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyaficloiudvkrorlcra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5YWZpY2xvaXVkdmtyb3JsY3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzY2NDgsImV4cCI6MjA2NzA1MjY0OH0.aKxm2YdyM8sZAZgRWjau9oc5tOwtm6qWYpw9vFFTqFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});